/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "stm32f412disco.h"
#include "stm32f412disco_gpio.h"
#include "001_led_toggle.h"
#include "002_led_joystik.h"
#include "003_led_interrupt.h"
#include "004_spi_tx_test.h"
#include "005_spi_tx_test.h"

//#define TEST_4
#define TEST_5

void EXTI9_5_IRQHandler(void)
{
	printf("%s\n", __func__);
	//led_interrupt_003_button_handler();
#ifdef TEST_4
	gpio_interrupt_004_handler();
#endif
#ifdef TEST_5
	gpio_interrupt_005_handler();
#endif
}

void SPI2_IRQHandler(void)
{
	printf("%s\n", __func__);
	spi_interrupt_005_handler();
}

int main(void)
{
	//led_toggle_001_main();
	//led_joystick_002_main();
	//led_interrupt_003_main();
#ifdef TEST_4
	spi_tx_test_004_main();
#endif
#ifdef TEST_5
	spi_tx_test_005_main();
#endif
    /* Loop forever */
	for(;;);
}
